-- ═════════════════════════════════════════════════════════════════════════════
-- Migration 080 (PROPOSED — DO NOT APPLY WITHOUT SEPARATE APPROVAL): revoke direct
-- authenticated/anon SELECT on the four Ralli Live tables, so ALL reads must go
-- through the safe SECURITY DEFINER RPCs (073 learner + 075 host/manager + 077
-- learner-joinable + 078 rejoin + 079 reveal/award). This closes the proven gap
-- where a same-tenant LEARNER can directly read question_snapshot, live_question,
-- and another player's answers.
--
-- PREREQUISITES (must be true before applying):
--   • 079 applied (reveal/award reads cut over) and 073/075/077/078 applied.
--   • Frontend has NO direct .select() on these tables (verified this turn — 0 remain).
--   • The ONE realtime postgres_changes subscription
--     (gameService.subscribeToLobbyParticipants on game_session_participants) is
--     removed and replaced by Presence + the rpc_lobby_participants poll — see below.
--       PROOF it needs SELECT: Supabase Realtime authorizes postgres_changes delivery
--       via the subscriber's role SELECT + RLS on the changed table; with SELECT
--       revoked from authenticated it delivers nothing. Smallest safe alternative:
--       drop that subscription (the host lobby already has realtime Presence for the
--       connected roster AND a 4s rpc_lobby_participants poll for the durable roster),
--       OR, if instant DB-insert notification is required, keep a dedicated
--       column-limited SELECT for realtime only (not adopted — Presence+poll suffice).
--
-- WHAT IS REVOKED (grant-level): SELECT on the four tables FROM authenticated, anon.
-- WHAT REMAINS: authenticated/anon keep INSERT/UPDATE where they already have them
--   (writes need no SELECT after this turn's return-path redesigns — saveGameAnswers
--   INSERT, participant upsert/left/heartbeat/completed UPDATE, session start/end/
--   phase/snapshot/cancel UPDATE). service_role keeps ALL privileges (background jobs
--   / edge). The SECURITY DEFINER RPCs run as their owner (postgres) and read the
--   tables regardless of the authenticated grant — so every safe read keeps working.
-- RLS: existing SELECT policies are left in place (defense-in-depth; moot once the
--   SELECT grant is gone). No policy is dropped. No column, table, or data changes.
--
-- END STATE — an ordinary learner can no longer directly read: question_snapshot,
-- live_question (live canonical answers), another player's answers, correctness/
-- points pre-reveal, manager analytics, or cross-player history. Completed learner
-- review still works via rpc_my_completed_session_review (073, SECURITY DEFINER).
--
-- ROLLBACK / OPERATIONAL RECOVERY (forward-only): if a safe RPC is found missing a
-- field a surface needs, ADD the field to that RPC (a new forward migration) rather
-- than re-granting table SELECT. Emergency re-grant (only if a Sev-1 read outage is
-- traced to this revocation): a one-line forward migration
--   GRANT SELECT ON public.<table> TO authenticated;  -- temporary, then re-close.
-- Realtime recovery: re-enable the removed subscription only alongside a re-grant.
-- ═════════════════════════════════════════════════════════════════════════════

-- REVOKE SELECT ON public.game_sessions             FROM authenticated, anon;
-- REVOKE SELECT ON public.game_answers              FROM authenticated, anon;
-- REVOKE SELECT ON public.game_players              FROM authenticated, anon;
-- REVOKE SELECT ON public.game_session_participants FROM authenticated, anon;
--
-- (Statements intentionally COMMENTED OUT: this file documents the exact plan and is
--  NOT to be applied. The real revocation migration will be authored + gated + tested
--  under separate approval once the realtime-subscription prerequisite is completed.)

SELECT '080 is a PROPOSAL — do not apply' AS note;
